/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

tasks.test {
    useJUnitPlatform()
}

buildscript {
    repositories {
        // Jenkins 插件仓库
        maven { url = uri("https://repo.jenkins-ci.org/public/") }
        // 阿里云镜像加速
        maven { url = uri("https://maven.aliyun.com/repository/gradle-plugin") }
        gradlePluginPortal()
        mavenCentral()
    }
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.jenkins-ci.org/public")
    }
}

dependencies {
    api(libs.com.aliyun.oss.aliyun.sdk.oss)
    api(libs.commons.lang.commons.lang)
    api(libs.org.jenkins.ci.plugins.jackson2.api)
    api(libs.org.jenkins.ci.plugins.workflow.workflow.cps)
    testImplementation(libs.org.jenkins.ci.main.jenkins.war)
    testImplementation(libs.org.jenkins.ci.main.jenkins.test.harness)
    testImplementation(libs.org.jenkins.ci.test.annotations)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.junit.vintage.junit.vintage.engine)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation(libs.org.junit.vintage.junit.vintage.engine)
    testImplementation(libs.org.jenkins.ci.main.jenkins.war.x1)
    testImplementation(libs.org.jenkins.ci.main.jenkins.test.harness)
    testImplementation(libs.org.jenkins.ci.test.annotations)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.junit.vintage.junit.vintage.engine)
    compileOnly(libs.org.jenkins.ci.main.jenkins.core)
    compileOnly(libs.jakarta.servlet.jakarta.servlet.api)
    compileOnly(libs.commons.logging.commons.logging)
    compileOnly(libs.org.jenkins.ci.main.jenkins.core.x1)
    compileOnly(libs.jakarta.servlet.jakarta.servlet.api)
    compileOnly(libs.commons.logging.commons.logging.x1)
}

group = "org.jenkins-ci.plugins"
version = "1.0.0-M1"
description = "Aliyun OSS Plugin for Jenkins"
java.sourceCompatibility = JavaVersion.VERSION_21

configurations.all {
    exclude(mapOf("group" to "javax.servlet", "module" to "javax.servlet-api"))
    exclude(mapOf("group" to "javax.servlet", "module" to "servlet-api"))
    exclude(mapOf("group" to "org.sonatype.sisu", "module" to "sisu-guice"))
    exclude(mapOf("group" to "log4j", "module" to "log4j"))
    exclude(mapOf("group" to "log4j", "module" to "log4j"))
    exclude(mapOf("group" to "commons-logging", "module" to "commons-logging"))
    exclude(mapOf("group" to "commons-logging", "module" to "commons-logging"))
    exclude(mapOf("group" to "org.apache.logging.log4j"))
    exclude(mapOf("group" to "org.jenkins-ci.main", "module" to "jenkins-test-harness"))
    exclude(mapOf("group" to "org.powermock", "module" to "powermock-api-easymock"))
    exclude(mapOf("group" to "org.powermock", "module" to "powermock-api-mockito2"))
    exclude(mapOf("group" to "org.powermock", "module" to "powermock-api-support"))
    exclude(mapOf("group" to "org.powermock", "module" to "powermock-classloading-base"))
    exclude(mapOf("group" to "org.powermock", "module" to "powermock-classloading-objenesis"))
    exclude(mapOf("group" to "org.powermock", "module" to "powermock-classloading-xstream"))
    exclude(mapOf("group" to "org.powermock", "module" to "powermock-core"))
    exclude(mapOf("group" to "org.powermock", "module" to "powermock-module-javaagent"))
    exclude(mapOf("group" to "org.powermock", "module" to "powermock-module-junit4"))
    exclude(mapOf("group" to "org.powermock", "module" to "powermock-module-junit4-common"))
    exclude(mapOf("group" to "org.powermock", "module" to "powermock-module-junit4-legacy"))
    exclude(mapOf("group" to "org.powermock", "module" to "powermock-module-junit4-rule"))
    exclude(mapOf("group" to "org.powermock", "module" to "powermock-module-junit4-rule-agent"))
    exclude(mapOf("group" to "org.powermock", "module" to "powermock-module-testng"))
    exclude(mapOf("group" to "org.powermock", "module" to "powermock-module-testng-agent"))
    exclude(mapOf("group" to "org.powermock", "module" to "powermock-module-testng-common"))
    exclude(mapOf("group" to "org.testng", "module" to "testng"))
}

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
        artifact(testsJar)
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
